apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Variables Required to run playbooks
  name: playbook-runner
labels:
  app.kubernetes.io/name: playbook-runner
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "10"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  stringData:
    k8s-api-token: ${K8S_TOKEN}
    cluster-environment: ${CLUSTER_ENV}
    aqua-admin-password: ${AQUA_ADMIN_PASSWORD}
    aqua-license: ${AQUA_LICENSE}
    aqua-registry-user: ${AQUA_REGISTRY_USER}
    aqua-registry-password: ${AQUA_REGISTRY_PASSWORD}
parameters:
- description: The name of the application for labelling all artifacts.
  displayName: Application Name
  name: NAME
  value: playbook-runner
- name: SUFFIX
  value: ''
- description: K8s Token Used for Authenticating against the cluster api.
  displayName: K8s Auth Token
  name: K8S_TOKEN
- description: OCP Cluster Environment (LAB|PROD)
  displayName: OCP Cluster Environment
  name: CLUSTER_ENV
  value: LAB
- description: Aqua Administrator Password Used in Aqua Playbook
  displayName: Aqua Administrator Password
  name: AQUA_ADMIN_PASSWORD
  value: secure1234
- description: Aqua License Used in Aqua Playbook
  displayName: Aqua License
  name: AQUA_LICENSE
- description: Aqua Registry Username (Email)
  displayName: Aqua Registry Username
  name: AQUA_REGISTRY_USER
- description: Aqua Registry Username (Email)
  displayName: Aqua Registry Username
  name: AQUA_REGISTRY_PASSWORD