---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
   - vars.yml
  vars:
    map_repo: "{{ list_git_repo | default(False) }}"
    ansible_command_timeout: 10
    current_list: {}
  tasks:
    - name: Pre-install packages
      pip:
        name:
          - jmespath
          - openshift

    - name: Get list of projects
      set_fact:
        projects: "{{ lookup('k8s', api_version='v1', kind='Project') }}" 

    - name: Output namespace basic info
      include_tasks: tasks/namespace_metadata.yml

    - name: Output all GitHub repo in namespaces
      include_tasks: tasks/repo_namespace_metadata.yml
      when: map_repo
