apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rmountie-04
resources:
- nats_cluster.yml
- prometheus.yml
- grafana.yml
# - argo_workflows.yml
- argo_events.yml


vars: 
- name: NAMESPACE
  objref:
    kind: Deployment 
    name: prometheus
    apiVersion: extensions/v1beta1
  fieldref: 
    fieldpath: metadata.namespace
    

images: 
  - name: argoproj/gateway-controller
    newTag: v0.12-rc
  - name: argoproj/sensor-controller
    newTag: v0.12-rc
  - name: argoproj/sensor
    newTag: v0.12-rc
  - name: argoproj/gateway
    newTag: v0.12-rc
  - name: grafana/grafana
    newTag: 6.5.2

configurations:
- kustomizeconfig/configmap.yml

