---
# Get all the relevant GH repo from the reference link from build configs:
- name: Get list of build configs
  set_fact:
    build_configs: "{{ lookup('k8s', api_version='v1', kind='BuildConfig') }}"

- name: Get list of build configs2
  set_fact:
    builds: "{{ build_configs | json_query(jmesquery) }}"
  vars:
    jmesquery: '[? metadata.namespace==`hmg6pw-tools`]'

- name: Create map
  include_tasks: create_map.yml
  with_items:
    - "{{ builds }}"
    # - "{{ build_configs }}"

- debug: msg="{{map}}"

- name: Create CSV output
  template: 
    src: templates/repo_namespace_metadata.csv.j2
    dest: output/repo_namespace_metadata.csv
