---
# Get all the relevant GH repo from the reference link from build configs:
- name: Get list of build configs
  set_fact:
    build_configs: "{{ lookup('k8s', api_version='v1', kind='BuildConfig') }}"

- name: Create map
  include_tasks: create_map.yml
  with_items:
    - "{{ build_configs }}"

- name: Create CSV output
  template: 
    src: templates/repo_namespace_metadata.csv.j2
    dest: "{{ output_dir }}/repo_namespace_metadata.csv"
    