apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rmountie-03
resources:
 - argo_events.yml
 - argo_workflows.yml
 - nats_cluster.yml


vars: 
# - name: OCP_PROJECT
#   objref:
#     kind: NetworkSecurityPolicy
#     name: egress-internet
#     apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1

images: 
  - name: argoproj/gateway-controller
    newTag: v0.12-rc
  - name: argoproj/sensor-controller
    newTag: v0.12-rc
  - name: argoproj/sensor
    newTag: v0.12-rc
  - name: argoproj/gateway
    newTag: v0.12-rc
  - name: grafana/grafana
    newTag: 6.5.2

# crds: 
# - kustomizeconfig/crd/networksecuritypolicy.json

configurations:
- kustomizeconfig/argo_cm.yml
# - kustomizeconfig/networksecuritypolicy.yml
