apiVerstion: v1
kind: List
items: 
- apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-internet
  spec:
    description: |
      allow the ocp-project namespace to talk to the internet.
    source:
      - - $namespace=ocp-project
    destination:
      - - ext:network=any
- apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
  spec:
    description: |
      allow the ocp-project namespace to talk to itself
    source:
      - - $namespace=ocp-project
    destination:
      - - $namespace=ocp-project
- apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
  spec:
    description: |
      allow ocp-project pods to talk to the k8s api
    destination:
    - - int:network=internal-cluster-api-endpoint
    source:
    - - $namespace=ocp-project