apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.12-rc"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway-with-standard-nats:example"
  eventProtocol:
    type: "NATS"
    nats:
      url: "nats://nats:4222"
      type: "Standard"
  triggers:
    - template:
        name: webhook-pod-trigger
        group: "batch"
        version: v1
        resource: jobs
        source:
          resource:
            apiVersion: batch/v1
            kind: Job
            metadata:
              generateName: hello-world-
            spec:
              template:
                spec:                
                  containers:
                    - name: hello-container
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
                      args: ["AHAH"]
                  restartPolicy: Never
      templateParameters:
        - src:
            event: "webhook-gateway-with-standard-nats:example"
            value: "message"
            path: message.body
          dest: source.resource.spec.template.spec.0.containers.command
          # - src:
          #     event: "webhook-gateway-with-standard-nats:example"
          #     path: message
          #   dest: source.resource.spec.containers.args
        # resourceParameters:
        # - src:
        #     event: "webhook-gateway-with-standard-nats:example"
        #     path: message
        #   dest: spec.command

    #     name: webhook-workflow-trigger
    #     group: argoproj.io
    #     version: v1alpha1
    #     resource: workflows
    #     source:
    #       resource:
    #         apiVersion: argoproj.io/v1alpha1
    #         kind: Workflow
    #         metadata:
    #           generateName: webhook-
    #         spec:
    #           entrypoint: whalesay
    #           arguments:
    #             parameters:
    #             - name: message
    #               # this is the value that should be overridden
    #               value: hello world
    #           templates:
    #           - name: whalesay
    #             inputs:
    #               parameters:
    #               - name: message
    #             container:
    #               image: docker/whalesay:latest
    #               command: [cowsay]
    #               args: ["{{inputs.parameters.message}}"]
