---
- block:
  - name: Generate console api auth token
    uri:
      url: 'https://{{ aqua_console_external_host }}/api/v1/login'
      method: POST
      body: 
        id: administrator
        password: '{{ aqua_administrator_password }}'
      body_format: json
      return_content: yes
    register: login_response
    ignore_errors: true
  
  - name: Set aqua_console_auth_token
    set_fact:
      aqua_console_auth_token: '{{ (login_response.content | from_json).token }}'
    when: login_response is succeeded
  
  - name: Show auth token
    debug: 
      var: aqua_console_auth_token
      verbosity: 1
  tags: 
    - agent
    - scanner
    - token
